### ISSUE TITLE
performance optimization

### ISSUE THREAD

**Issue by baslr** [TheStrath/ScanningRadar#1]
due to my investigation how to integrate the AutoDesignate mod with the scanning radar mod I noticed that the scanning radar mod is calling chart() for every tile. One chart call reveals a complete chunk. One chunk is 32 x 32 tiles.
That means only 1/1024 chart() calls are necessary to achieve the desired result.

I did a quick test and set the step wide to 32 and yi / xi to 32 respectively to -32 in the function plotLineHigh / plotLineLow. This gives me almost the same result. Just a few offset problems left.

**Comment by TheStrath** [comment]
Thanks for the find. I'll make a correction. Though it should be pointed out that it only calls chart() at most 45 extra times per chunk ;)

**Comment by TheStrath** [comment]
Corrected in version 0.2.8
